BreweryState.create(name: "Alabama")
BreweryState.create(name: "Alaska")
BreweryState.create(name: "Arizona")
BreweryState.create(name: "Arkansas")
BreweryState.create(name: "California")
BreweryState.create(name: "Colorado")
BreweryState.create(name: "Connecticut")
BreweryState.create(name: "Delaware")
BreweryState.create(name: "Florida")
BreweryState.create(name:  "Georgia")
BreweryState.create(name:  "Hawaii")
BreweryState.create(name:  "Idaho")
BreweryState.create(name:  "Illinois")
BreweryState.create(name:  "Indiana")
BreweryState.create(name:  "Iowa")
BreweryState.create(name:  "Kansas")
BreweryState.create(name:  "Kentucky")
BreweryState.create(name:  "Louisiana")
BreweryState.create(name:  "Maine")
BreweryState.create(name:  "Maryland")
BreweryState.create(name:  "Massachusetts")
BreweryState.create(name:  "Michigan")
BreweryState.create(name:  "Minnesota")
BreweryState.create(name:  "Mississippi")
BreweryState.create(name:  "Missouri")
BreweryState.create(name:  "Montana")
BreweryState.create(name:  "Nebraska")
BreweryState.create(name:  "Nevada")
BreweryState.create(name:  "New Hampshire")
BreweryState.create(name:  "New Jersey")
BreweryState.create(name:  "New Mexico")
BreweryState.create(name:  "New York")
BreweryState.create(name:  "North Carolina")
BreweryState.create(name:  "North Dakota")
BreweryState.create(name:  "Ohio")
BreweryState.create(name:  "Oklahoma")
BreweryState.create(name:  "Oregon")
BreweryState.create(name:  "Pennsylvania")
BreweryState.create(name:  "Rhode Island")
BreweryState.create(name:  "South Carolina")
BreweryState.create(name:  "South Dakota")
BreweryState.create(name:  "Tennessee")
BreweryState.create(name:  "Texas")
BreweryState.create(name:  "Utah")
BreweryState.create(name:  "Vermont")
BreweryState.create(name:  "Virginia")
BreweryState.create(name:  "Washington")
BreweryState.create(name:  "West Virginia")
BreweryState.create(name:  "Wisconsin")
BreweryState.create(name:  "Wyoming")

User.create(name: "Homer Simpson", email: "simpson@email.com", password: "12345")
User.create(name: "Norm Peterson", email: "peterson@email.com", password: "12345")
User.create(name: "Randy Marsh", email: "marsh@email.com", password: "12345")
User.create(name: "Cliff Clavin", email: "clavin@email.com", password: "12345")
User.create(name: "Barney Grumble", email: "grumbl@email.com", password: "12345")
User.create(name: "Janis Joplin", email: "joplin@email.com", password: "12345")
User.create(name: "Charles Bukowski", email: "bukowski@email.com", password: "12345")
User.create(name: "Lindsay Lohan", email: "hemingway@email.com", password: "12345")
User.create(name: "Dean Martin", email: "martin@email.com", password: "12345")
User.create(name: "Mike", email: "mike@email.com", admin: true, password: "12345")
User.create(name: "Troll", email: "troll@troll.com", password: "12345")
User.create(name: "Jennifer Lawrence", email: "lawrenc@email.com", password: "12345")

BreweryThread.create(brewery_state_id: 5, user_id: 10, brewery: "Stone Brewing Co.")
BreweryThread.create(brewery_state_id: 21, user_id: 2, brewery: "Samuel Adams Brewery")
BreweryThread.create(brewery_state_id: 6, user_id: 3, brewery: "New Belgium Brewing Company")
BreweryThread.create(brewery_state_id: 8, user_id: 8, brewery: "Dogfish Head Brewery")
BreweryThread.create(brewery_state_id: 37, user_id: 1, brewery: "Duff Brewery")
BreweryThread.create(brewery_state_id: 43, user_id: 7, brewery: "Live Oak Brewing Co.")
BreweryThread.create(brewery_state_id: 5, user_id: 10, brewery: "Ballast Point Brewery, Long Beach")
BreweryThread.create(brewery_state_id: 5, user_id: 10, brewery: "Sierra Nevada Brewing Co.")
BreweryThread.create(brewery_state_id: 21, user_id: 4, brewery: "Samuel Adams Brewery")
BreweryThread.create(brewery_state_id: 37, user_id: 5, brewery: "Deschutes Brewery")
BreweryThread.create(brewery_state_id: 32, user_id: 9, brewery: "Brooklyn Brewery")
BreweryThread.create(brewery_state_id: 5, user_id: 6, brewery: "Belmont Brewing Company")
BreweryThread.create(brewery_state_id: 25, user_id: 1, brewery: "Springfield Brewing Company")
BreweryThread.create(brewery_state_id: 17, user_id: 12, brewery: "Browning's Brewery at Louisville Slugger Field")
BreweryThread.create(brewery_state_id: 49, user_id: 11, brewery: "Thirsty Pagan Brewing Co")
BreweryThread.create(brewery_state_id: 9, user_id: 9, brewery: "Tampa Bay Brewing Co.")
BreweryThread.create(brewery_state_id: 28, user_id: 7, brewery: "Sin City Brewing Co")

Post.create(brewery_thread_id: 1, user_id: 10, body: "While visiting the Golden State, you would be doing yourself a disservice if you didn’t stop by Stone Brewing Company in Escondido. Famous for its bold, hoppy beers, this brewery is easily one of the most unique tours you can take. But make sure you get there early, as the tours usually sell out rather quickly and are limited to only 25 people at a time. Tours only cost $3 for adults and come with a free tasting glass and four 4oz beers of your choice. There’s a wide range of public tour times that stretch over all seven days of the week. But, if you’re looking for the full ‘Stone experience’, you would be better served booking a private tour through their website. The outdoor garden, featuring waterfalls, vegetation and rock formations, creates a unique atmosphere to relax and enjoy a great-tasting brew!")
Post.create(brewery_thread_id: 2, user_id: 2, body: "Founded in 1984, Samuel Adams Brewery exists because flavorful beer was hard to come by at that time. The success of the brewery was all due to a family beer recipe that dated back to the 1870’s, plus a lot of hard work from the great-great grandson of the man that came up with the recipe. Almost thirty years later, that same recipe, what we now know as Samuel Adams Boston Lager, is sold all over America and over twenty countries. There is simply no “Best Brewery Tour List” that does not contain Samuel Adams. Tours of the brewery start every 45 minutes, Monday through Saturday. Unless you have a large group, Samuel Adams Brewery does not take reservations. Because of this, it is wise to show up very early, especially on Saturdays. During your brewery tour, you’ll learn all about the craft brewing process, the history of Samuel Adams and taste a couple of their brews. This is a must-see brewery tour for every beer geek.")
Post.create(brewery_thread_id: 3, user_id: 3, body: "If you ever find yourself in Fort Collins, Colorado, you would be doing yourself a disservice if you didn’t stop by and visit the New Belgium Brewing Company. Officially launched in 1991, this brewery has become so popular that they now distribute in 34 states, and they recently confirmed that they’ll be distributing in Ohio soon. If you want to take a brewery tour, you’re going to need to book it far in advance. To do this, just log onto their website and check out their tour calender. Brewery tours happen Tuesday through Saturday and depart every half hour starting at 11am, with the last one departing at 4:30pm. The tours are free, open to all ages and generally last about 90 minutes. During your tour you will be able to sample the tasty beer.")
Post.create(brewery_thread_id: 4, user_id: 8, body: "Founded in 1995, the Dogfish Head Brewery is a wildly popular brewery in Milton, Deleware that was once deemed “America’s most interesting and adventurous small brewery” by one of the world’s most respected beer writers. To take a guided tour of this brewery, you need to reserve your tickets online. They allow walk-ins, but only if there are spots available. They offer tours every half hour from Tuesday to Saturday. The tour times range based on the day, but Dogfish offers tours from 11am-4pm during those days.")
Post.create(brewery_thread_id: 5, user_id: 1, body: "Grab an icy cold glass of My favorite drink and relax in the Duff Brewery beer garden. This open-air bar provides lotsa seating and waterfront tables with umbrellas, making it the perfect place to sip some suds and watch popular clips of The Simpsons™. You’ll be surrounded by topiaries of the beloved Seven Duffs: Tipsy, Queasy, Surly, Sleazy, Edgy, Dizzy, and Remorseful. Become the eighth Duff and pose for a picture with the giant statue of Duffman himself. “Oh Yeah!”")
Post.create(brewery_thread_id: 6, user_id: 7, body: "Located in the heart of Texas, Live Oak Brewing Company is a small microbrewery located in Austin, TX. This brewery is unlike all others on this list, because they utilize an “old-world style of brewing” that you hardly find in the United States today. Founded by two homebrewers in Austin, Live Oak Brewing creates some very tasty beer, in very limited quantities. Brewery tours can be somewhat tricky to get into, but absolutely worth the effort if you can pull it off. In order to get in on this free tour, you gotta keep a close eye on their website. They will announce when their upcoming tours are, and then post a “reservation link” at 8am the Thursday before the tour date. If you can’t get in for a tour, they do offer a free ‘virtual tour’ on their website.")
Post.create(brewery_thread_id: 15, user_id: 11, body: "I'm surrounded by drunks!")
Post.create(brewery_thread_id: 7, user_id: 10, body: "Iconic brewery with beautiful views of the ocean and sunset. They have two floors, so if you get there early enough, grab a spot upstairs! The service at the upstairs bar is pretty slow though, so I'd recommend ordering downstairs and just bringing stuff up. You usually see about 2-3 employees up there, but only one of them is taking orders. My friend and I went up to the bar to grab a menu and they rudely told us that there's a line to order beer. Sorry, we just wanted to see a menu up close... There was no one in line at this time (4pm on a weekday). Most of their beers are IPAs, so if you're like me, you'll be hard pressed to find something you like. They also have a bunch of ciders and kolsches too. Nevertheless, I still come to Ballast Point for the views and enjoyment with friends. They have their own parking lot that is shared with a few other businesses next door, but I've honestly never paid attention to anything other than Ballast Point.")
Post.create(brewery_thread_id: 8, user_id: 10, body: "At the Sierra Nevada Brewing Company in Chico, California, you can enjoy a variety of craft brews while touring this popular brewery. The tour takes you through all the stages of brewing beer. See and smell fresh hops and witness the fermentation process. After the tour, enjoy samples of famous beers sold by the brewery. If you are hungry for more, stop by the restaurant for a hearty meal. If you do, be sure to ask about pairing different beers with the restaurant dishes to find a brew that complements your menu choice.")
Post.create(brewery_thread_id: 9, user_id: 4, body: "We went down for the tour early. Having read other reviews indicating that parking is an issue. They were not kidding very small lot, first come first serve. Very personable tour guides and very informative. We’d go back!")
Post.create(brewery_thread_id: 10, user_id: 5, body: "Founded in 1988 as a tiny brew pub in downtown Bend, Oregon, the Deschutes Brewery has since grown into one of the most popular craft brewers in America. Five years after opening the brew pub, Deschutes moved into a large brewery along the Deschutes River in order to meet the high demand for their brew. Brewery tours are free and depart on the hour, every hour between 1-4pm. However, it’s wise to get there early because only fifteen people are allowed to go on each guided tour. This means that only sixty people a day will get to walk through and fully experience the brewery. Don’t fret if you can’t get in, as beer tastings still happen whether you make it into the brewery tour or not. You also have the opportunity to waste a lot of time – and money – in their gift shop.")
Post.create(brewery_thread_id: 11, user_id: 9, body: "Since its founding in the late eighties, the Brooklyn Brewery has been brewing some of the most flavorful beer in the Big Apple. In fact, over the last couple of decades, beer enthusiasts across America have discovered how tasty their beer really is, which is why the Brooklyn Brewery now distributes its beer in over 25 states, as well as 20 countries. The brewery offers tours every day of the week except Fridays, however if you plan on dropping by Monday-Thursday, you will need to make a reservation online and pay $8 to get in. On the weekends, the brewery is open to the public with no admission fee, with tours starting on the hour throughout most of the day. No trip to NYC is complete, without checking out this brewery.")
Post.create(brewery_thread_id: 13, user_id: 1, body: "Mmmmm...Beer. Doh!")
Post.create(brewery_thread_id: 12, user_id: 6, body: "Place is still just as chill, and the people just as friendly and just as knowledgeable, but I am happy to report, they now also have a wider variety of styles. See my previous review for comments on several, but they do now also have a couple different IPAs, which I didn't try because IPAs are terrible (:p), but also, happily the coffee amber I'd wanted to try the previous time. I will say, I was hoping for more coffee - the coffee is there, but subtle, being there more to mellow out any harshness of the beer. It is a very solid amber, though (I like it more than the original amber that they also have, which I tried last time and also enjoyed.")
Post.create(brewery_thread_id: 1, user_id: 9, body: "Ain't this place a kick in the head!")
Post.create(brewery_thread_id: 2, user_id: 4, body: "Aaaahhh, you used to be able to drink here in uniform. Yessiree!")
Post.create(brewery_thread_id: 7, user_id: 1, body: "Mmmmm...Beer. Doh!")
Post.create(brewery_thread_id: 8, user_id: 3, body: "This place is ssoooo PC!")
Post.create(brewery_thread_id: 9, user_id: 7, body: "I don't know how many bottles of beer I have consumed while waiting for things to get better.")
Post.create(brewery_thread_id: 14, user_id: 12, body: "I’ve only been in love with a beer bottle and a mirror. Originally, I didn't even plan on stoping at Browning's while I visited Louisville. However, I stoped by with my girlfriend and her family for lunch since we were already downtown. Just so you know if you are looking for the place, it's located within the Louisville Bat's ballpark complex. When I called for directions they failed to mention that they were located within a very easily found landmark. That said, I was resonably impressed with Browning's. The atmosphere has a slightly upscale trendy kind of feel, almost like your favorite steakhouse with craftbeer.")
Post.create(brewery_thread_id: 16, user_id: 9, body: "I have respect for beer. I have respect for Florida. Love to be here. It's so great to be here. Really, it is... so great... slurp.")
Post.create(brewery_thread_id: 17, user_id: 7, body: "The craft brewery was launched by award-winning brewer Richard Johnson in 2003, and beers are produced in small batches using premium raw materials and a strict adherence to the Rheinheitsgebot, a 1516 German beer purity law.")
Post.create(brewery_thread_id: 1, user_id: 11, body: "You should quit drinking.")
Post.create(brewery_thread_id: 2, user_id: 11, body: "You should quit drinking.")
Post.create(brewery_thread_id: 3, user_id: 11, body: "You should quit drinking.")
Post.create(brewery_thread_id: 4, user_id: 11, body: "You should quit drinking.")
Post.create(brewery_thread_id: 6, user_id: 11, body: "You should quit drinking.")
Post.create(brewery_thread_id: 14, user_id: 11, body: "You should quit drinking.")
Post.create(brewery_thread_id: 9, user_id: 11, body: "You should quit drinking.")
Post.create(brewery_thread_id: 10, user_id: 11, body: "You should quit drinking.")
Post.create(brewery_thread_id: 11, user_id: 11, body: "You should quit drinking.")
Post.create(brewery_thread_id: 8, user_id: 11, body: "You should quit drinking.")
