
BreweryState.create(name: "Alabama")
BreweryState.create(name: "Alaska")
BreweryState.create(name: "Arizona")
BreweryState.create(name: "Arkansas")
BreweryState.create(name: "California")
BreweryState.create(name: "Colorado")
BreweryState.create(name: "Connecticut")
BreweryState.create(name: "Delaware")
BreweryState.create(name: "Florida")
BreweryState.create(name:  "Georgia")
BreweryState.create(name:  "Hawaii")
BreweryState.create(name:  "Idaho")
BreweryState.create(name:  "Illinois")
BreweryState.create(name:  "Indiana")
BreweryState.create(name:  "Iowa")
BreweryState.create(name:  "Kansas")
BreweryState.create(name:  "Kentucky")
BreweryState.create(name:  "Louisiana")
BreweryState.create(name:  "Maine")
BreweryState.create(name:  "Maryland")
BreweryState.create(name:  "Massachusetts")
BreweryState.create(name:  "Michigan")
BreweryState.create(name:  "Minnesota")
BreweryState.create(name:  "Mississippi")
BreweryState.create(name:  "Missouri")
BreweryState.create(name:  "Montana")
BreweryState.create(name:  "Nebraska")
BreweryState.create(name:  "Nevada")
BreweryState.create(name:  "New Hampshire")
BreweryState.create(name:  "New Jersey")
BreweryState.create(name:  "New Mexico")
BreweryState.create(name:  "New York")
BreweryState.create(name:  "North Carolina")
BreweryState.create(name:  "North Dakota")
BreweryState.create(name:  "Ohio")
BreweryState.create(name:  "Oklahoma")
BreweryState.create(name:  "Oregon")
BreweryState.create(name:  "Pennsylvania")
BreweryState.create(name:  "Rhode Island")
BreweryState.create(name:  "South Carolina")
BreweryState.create(name:  "South Dakota")
BreweryState.create(name:  "Tennessee")
BreweryState.create(name:  "Texas")
BreweryState.create(name:  "Utah")
BreweryState.create(name:  "Vermont")
BreweryState.create(name:  "Virginia")
BreweryState.create(name:  "Washington")
BreweryState.create(name:  "West Virginia")
BreweryState.create(name:  "Wisconsin")
BreweryState.create(name:  "Wyoming")